title: SudoJunior
description: |
  I am a Systems Programmer focused on Backend and DevOps infrastructure with familiarity of Unity / C#, TypeScript and the Discord API. I run a community named TinkerStorm on [Discord](https://discord.gg/Bb3JQQG) and [GitHub](https://github.com/TinkerStorm) which is dedicated to researching the decisions of communities and their players.

permalink: /:year/:month/:day/:title