title: SudoJunior
description: |
  Systems Programmer; Backend & DevOps Engineer; Unity, JavaScript & Web Experiments... Student.

  I run a discord community named [TinkerStorm](https://discord.gg/Bb3JQQG) on [GitHub](https://github.com/TinkerStorm) which is dedicated to researching the decisions of communities and their players.

permalink: /:year/:month/:day/:title