title: SudoJunior
description: |
  I specialise in designing and building engaging digital experiences, with a strong focus on game development and interactive applications. I enjoy tackling complex logic, refining user interactions, and crafting systems that make gameplay feel seamless and immersive.

  Beyond coding, I run a community named TinkerStorm on [Discord](https://discord.gg/Bb3JQQG) and [GitHub](https://github.com/TinkerStorm) which is dedicated to researching the decisions of communities and their players.

# I am a Systems Programmer focused on Backend and DevOps infrastructure with familiarity of Unity / C#, TypeScript and the Discord API. I run a community named TinkerStorm on [Discord](https://discord.gg/Bb3JQQG) and [GitHub](https://github.com/TinkerStorm) which is dedicated to researching the decisions of communities and their players.##

permalink: /:year/:month/:day/:title
